### ISSUE TITLE
Namenotfoundexception

### ISSUE THREAD

**Issue by joshln87** [saket/Better-Link-Movement-Method#17]
Hi, I got this crash. Any ideas?

`Caused by android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:138)
       at android.webkit.WebViewFactory.fetchPackageInfo(WebViewFactory.java:107)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:183)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:158)
       at android.webkit.WebView.getFactory(WebView.java:2277)
       at android.webkit.WebView.findAddress(WebView.java:1683)
       at android.text.util.Linkify.gatherMapLinks(Linkify.java:472)
       at android.text.util.Linkify.addLinks(Linkify.java:237)
       at android.text.util.Linkify.addLinks(Linkify.java:267)
       at me.saket.bettermovementmethod.BetterLinkMovementMethod.addLinks(BetterLinkMovementMethod.java:202)
       at me.saket.bettermovementmethod.BetterLinkMovementMethod.rAddLinks(BetterLinkMovementMethod.java:194)
       at me.saket.bettermovementmethod.BetterLinkMovementMethod.rAddLinks(BetterLinkMovementMethod.java:190)
       at me.saket.bettermovementmethod.BetterLinkMovementMethod.rAddLinks(BetterLinkMovementMethod.java:190)
       at me.saket.bettermovementmethod.BetterLinkMovementMethod.linkify(BetterLinkMovementMethod.java:104)`

**Comment by saket** [comment]
Sorry for the late response, I was attending droidcon Berlin and traveling around. This crash looks very weird. Linkify internally depends on WebView for identifying links. Does this happen constantly? 

This slightly related answer on SO indicates that this might be an occasional crash that you could ignore: https://stackoverflow.com/questions/29575313/namenotfoundexception-webview

**Comment by saket** [comment]
Closing due to inactivity. Feel free to re-open if you have more questions.
